apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  DB_NAME: wordpress
  DB_USERNAME: wordpress
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  DB_PASSWORD: YmlyZHNhcmVudHJlYWw=